/**
 * The machine-written half of an entry's QA.md.
 *
 * The hand-authored spot-check tables were the weak link in the publish gate:
 * they asserted that values matched the source when no capture existed to
 * compare against, and their wording went stale the moment a token changed.
 * This section is regenerated from an actual verification run, so it can only
 * ever describe what was really checked.
 */

export interface VerificationSummary {
  slug: string;
  sourceType: string;
  verifiedAt: string;
  sources: string[];
  sourceColorCount: number;
  colors: Array<{ token: string; value: string; nearest: string | null; verdict: string }>;
  score: { exact: number; close: number; drift: number; unmatched: number; total: number };
}

const HEADING = "## Source verification (automated)";

/** Render the verification section for an entry. */
export function buildVerificationSection(summary: VerificationSummary): string {
  const { score } = summary;
  const grounded = score.exact + score.close;
  const rows = summary.colors
    .map(
      (c) =>
        `| \`colors.${c.token}\` | ${c.value.toUpperCase()} | ${
          c.nearest ? c.nearest.toUpperCase() : "—"
        } | ${c.verdict} |`,
    )
    .join("\n");

  const sourceList = summary.sources
    .slice(0, 8)
    .map((s) => `  - ${s}`)
    .join("\n");
  const more = summary.sources.length > 8 ? `\n  - …and ${summary.sources.length - 8} more` : "";

  return `${HEADING}

> Generated by \`pnpm pipeline verify ${summary.slug}\` on ${summary.verifiedAt}. Every
> color below was compared against a fresh extraction of the cited source using
> CIEDE2000: **exact** identical, **close** ΔE ≤ 2, **drift** ΔE ≤ 5,
> **unmatched** ΔE > 5. Re-run the command to refresh this section.

- Source type: \`${summary.sourceType}\`
- Distinct colors recovered from source: ${summary.sourceColorCount}
- Colors grounded in source: **${grounded}/${score.total}**
  (exact ${score.exact} · close ${score.close} · drift ${score.drift} · unmatched ${score.unmatched})
- Files read:
${sourceList}${more}

| Token | Value in file | Nearest source color | Verdict |
| --- | --- | --- | --- |
${rows}
`;
}

/**
 * Replace an entry's verification section, or append one. Everything a human
 * wrote above it is preserved — only the generated block is owned by the tool.
 */
export function upsertVerificationSection(qa: string, section: string): string {
  const start = qa.indexOf(HEADING);
  if (start === -1) {
    const signOff = qa.indexOf("## Sign-off");
    if (signOff === -1) return `${qa.trimEnd()}\n\n${section}`;
    return `${qa.slice(0, signOff)}${section}\n${qa.slice(signOff)}`;
  }
  // Ends at the next top-level heading, or the end of the file.
  const rest = qa.slice(start + HEADING.length);
  const nextHeading = rest.search(/\n## /);
  const end = nextHeading === -1 ? qa.length : start + HEADING.length + nextHeading + 1;
  return `${qa.slice(0, start)}${section}${nextHeading === -1 ? "" : `\n${qa.slice(end)}`}`;
}
